#pragma once

#include <boost/program_options.hpp>

namespace RMC {

// Special Quasirandom Structure (SQS) generation.
//
// Method references:
//   [1] A. Zunger, S.-H. Wei, L. G. Ferreira, and J. E. Bernard, "Special
//       Quasirandom Structures," Phys. Rev. Lett. 65, 353-356 (1990).
//       doi:10.1103/PhysRevLett.65.353
//   [2] A. van de Walle, P. Tiwary, M. de Jong, D. L. Olmsted, M. Asta,
//       A. Dick, D. Shin, Y. Wang, L.-Q. Chen, and Z.-K. Liu, "Efficient
//       stochastic generation of special quasirandom structures,"
//       Calphad 42, 13-18 (2013). doi:10.1016/j.calphad.2013.06.006
//
// The mcsqs algorithm [2] is implemented in the ATAT package; the cluster basis
// here is built using ATAT's corrdump, which is run as a separate external tool
// (installed separately, not bundled with this project). ATAT is licensed
// CC BY-ND 4.0.

// Application driver for the mcsqs_rmc executable — an advanced Special
// Quasi-random Structure (SQS) search built on the RMC engine. It replaces
// ATAT's mcsqs MC loop with a pluggable acceptance policy (greedy / metropolis
// / anneal, the default annealing mirroring ATAT's simulated annealing),
// adaptive site selection, a batch-buffered RNG, and optional island-model
// ensemble parallelism.
//
// Inputs arrive via one of two pipelines:
//   • corrdump (--lattice): an rndstr.in primitive lattice is expanded to a
//     supercell and clusters are generated by running corrdump; the result is
//     cross-checked against corrdump's own correlations.
//   • legacy (--structure/--clusters/--species): a fixed-site PDB plus a
//     pre-enumerated cluster-orbit file and binary/linear species map, for when
//     corrdump is unavailable. Both pipelines build the same cluster basis.
//
// main() just constructs one of these and forwards argc/argv to run().
class McsqsRunner {
public:
  McsqsRunner();
  // exit code (0 on success, 1 on error).
  int run(int argc, char **argv);

private:
  boost::program_options::options_description options_;
};

} // namespace RMC
