#pragma once

#include <boost/program_options.hpp>

namespace RMC {

// Application driver for the mcsqs_rmc executable — an advanced Special
// Quasi-random Structure (SQS) search built on the RMC engine. It replaces
// ATAT's mcsqs MC loop with a pluggable acceptance policy (greedy / metropolis
// / anneal, the default annealing mirroring ATAT's simulated annealing),
// adaptive site selection, a batch-buffered RNG, and optional island-model
// ensemble parallelism.
//
// Inputs arrive one of two ways:
//   - ATAT pipeline (--lattice): an rndstr.in primitive lattice is expanded to
//     a supercell and clusters are generated by running corrdump; the result is
//     cross-checked against corrdump's own correlations.
//   - Legacy (--structure + --clusters + --species): an explicit PDB plus a
//     pre-computed cluster-orbit file and species occupation map.
//
// main() just constructs one of these and forwards argc/argv to run().
class McsqsRunner {
public:
  McsqsRunner();
  // exit code (0 on success, 1 on error).
  int run(int argc, char **argv);

private:
  boost::program_options::options_description options_;
};

} // namespace RMC
