# Generated by tools/fix_core_stubs.py -- do not edit by hand.
# CI regenerates this and fails on a diff.
"""
The SQS (special quasirandom structure) pipeline. Import rmc.mcsqs instead.
"""
from __future__ import annotations
import collections.abc
import numpy
import numpy.typing
import rmc._core
import typing
__all__: list[str] = ['AtatLattice', 'EnumeratedSqs', 'LatticeSite', 'enumerate', 'parse_lattice', 'parse_lattice_text', 'write_str_out']
class AtatLattice:
    """
    An ATAT rndstr.in lattice: axes, the cell in units of axes, sites, and every species label, sorted.
    """
    def __init__(self, *, axes: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"] = ..., cell: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"] = ..., sites: collections.abc.Sequence[LatticeSite] = [], labels: collections.abc.Sequence[str] = []) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def occupation_index(self, species: str) -> int:
        """
        The species' rank in labels, or -1.
        """
    @property
    def axes(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
        ...
    @axes.setter
    def axes(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"]) -> None:
        ...
    @property
    def cell(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
        ...
    @cell.setter
    def cell(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"]) -> None:
        ...
    @property
    def labels(self) -> list[str]:
        ...
    @labels.setter
    def labels(self, arg0: collections.abc.Sequence[str]) -> None:
        ...
    @property
    def sites(self) -> list[LatticeSite]:
        ...
    @sites.setter
    def sites(self, arg0: collections.abc.Sequence[LatticeSite]) -> None:
        ...
class EnumeratedSqs:
    """
    A supercell with a random start and its cluster orbits: everything a ClusterCorrelationConstraint needs (occ_index, table, orbits).
    """
    structure: rmc._core.AtomicStructure
    def __init__(self, *, structure: rmc._core.AtomicStructure = ..., orbits: collections.abc.Sequence[rmc._core.ClusterOrbit] = [], occ_index: collections.abc.Mapping[str, typing.SupportsInt | typing.SupportsIndex] = {}, table: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"]] = [], axes: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"] = ..., supercell: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"] = ..., frac_positions: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]] = []) -> None:
        ...
    def __repr__(self) -> str:
        ...
    @property
    def axes(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
        ...
    @axes.setter
    def axes(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"]) -> None:
        ...
    @property
    def frac_positions(self) -> list[typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]]:
        ...
    @frac_positions.setter
    def frac_positions(self, arg0: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]]) -> None:
        ...
    @property
    def occ_index(self) -> dict[str, int]:
        ...
    @occ_index.setter
    def occ_index(self, arg0: collections.abc.Mapping[str, typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
    @property
    def orbits(self) -> list[rmc._core.ClusterOrbit]:
        ...
    @orbits.setter
    def orbits(self, arg0: collections.abc.Sequence[rmc._core.ClusterOrbit]) -> None:
        ...
    @property
    def supercell(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
        ...
    @supercell.setter
    def supercell(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"]) -> None:
        ...
    @property
    def table(self) -> list[typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]]:
        ...
    @table.setter
    def table(self, arg0: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"]]) -> None:
        ...
class LatticeSite:
    """
    A lattice site: fractional position and the (species, fraction) pairs that may occupy it.
    """
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: LatticeSite) -> bool:
        ...
    def __init__(self, *, frac: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"] = ..., occ: collections.abc.Sequence[tuple[str, typing.SupportsFloat | typing.SupportsIndex]] = []) -> None:
        ...
    def __repr__(self) -> str:
        ...
    @property
    def frac(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    @frac.setter
    def frac(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> None:
        ...
    @property
    def occ(self) -> list[tuple[str, float]]:
        ...
    @occ.setter
    def occ(self, arg0: collections.abc.Sequence[tuple[str, typing.SupportsFloat | typing.SupportsIndex]]) -> None:
        ...
def enumerate(lattice: AtatLattice, supercell: typing.Annotated[numpy.typing.ArrayLike, numpy.int32, "[3, 3]"], diameters: collections.abc.Mapping[typing.SupportsInt | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex], *, seed: typing.SupportsInt | typing.SupportsIndex = 42) -> EnumeratedSqs:
    """
    Build the supercell (a (3, 3) integer matrix of lattice.cell) with a random start at the target composition, and enumerate cluster orbits up to diameters {body: max diameter in Angstrom}.
    """
def parse_lattice(path: os.PathLike | str | bytes) -> AtatLattice:
    """
    Read an ATAT rndstr.in file.
    """
def parse_lattice_text(text: str) -> AtatLattice:
    """
    Parse rndstr.in text.
    """
def write_str_out(path: os.PathLike | str | bytes, axes: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"], supercell: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"], positions: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]], species: collections.abc.Sequence[str]) -> None:
    """
    Write an ATAT str.out (positions in units of axes).
    """
