foreach(ex
    translations
    rotations
    bonds_constraint
    angles_constraint
    dihedral_constraint
    improper_constraint
    coordination_constraint
    smart_selector
    atomic_niti
    molecular_co2
    molecular_thf
    si_ox_nanosphere
    agitations
    axis_translations
    orientation
    swap_centers
    generator_collector
    path_generators
    reduced_sq)
    add_subdirectory(${ex})
endforeach()
