#!/usr/bin/env python3
"""Generate and narrow the type stubs for the rmc._core extension.

Runs pybind11-stubgen and then fixes up what it cannot get right on its own
(seitz's tool, with RMC's names):

  * ``--enum-class-locations`` for every py::native_enum, because a default
    argument of enum type is rendered as its repr and stubgen must be told where
    the class lives to turn it back into an expression, or it exits non-zero.
    The list is read off the imported module (the mcsqs submodule included), so
    a binding that adds an enum does not also have to edit this file.
  * Array annotations, which stubgen writes as a bare ``numpy.ndarray``. The
    bindings hand back float64 coordinates and curves, int32 species codes and
    uint64 index arrays, so those become ``numpy.typing.NDArray`` aliases.
    Shape is not expressible in today's numpy typing; the docstrings say it.
  * The version, which stubgen copies out as a literal. weekly-release.yml bumps
    project() without rebuilding, so a committed ``'1.0.1'`` would fail CI's
    diff gate on every release commit. The annotation stays; the value goes.

Run it through ``uv run``, always: the output depends on the interpreter, and
CI regenerates under uv and fails on a diff. It imports the module, so
PYTHONPATH must point at a build tree (and a GCC 15 build under an older
system libstdc++ needs the LD_PRELOAD ctest sets):

    PYTHONPATH=build/python/python uv run python tools/fix_core_stubs.py
"""

import enum
import importlib
import inspect
import pathlib
import re
import subprocess
import sys

# A package of stubs, not one file: _core has the mcsqs submodule, so stubgen
# writes a directory. It sits beside _core.cpython-*.so without shadowing it --
# a real module wins over a directory with no __init__.py -- which
# python/tests/test_stubs.py pins.
STUB_DIR = pathlib.Path("python/rmc/_core")
MODULE = "rmc._core"
OUT_DIR = "python"

HEADER = """# Generated by tools/fix_core_stubs.py -- do not edit by hand.
# CI regenerates this and fails on a diff.
"""

SUBSTITUTIONS = tuple(
    (rf"numpy\.ndarray\[numpy\.{dtype}(?:\[[^\]]*\])*\]", f"numpy.typing.NDArray[numpy.{dtype}]")
    for dtype in ("float64", "int32", "uint64")
) + ((r"^(__version__: str) = '[^']*'$", r"\1"),)

#: enum.Enum, IntEnum and friends: in the namespace only because the enums the
#: module defines derive from them, not something to place.
_ENUM_BASES = frozenset(
    v for v in vars(enum).values() if isinstance(v, type) and issubclass(v, enum.Enum)
)


def enum_locations() -> list[str]:
    """``Name:module`` for every enum the extension exports, at any depth."""
    root = importlib.import_module(MODULE)
    submodules = [
        m for m in vars(root).values()
        if inspect.ismodule(m) and m.__name__.startswith(f"{MODULE}.")
    ]
    return sorted(
        f"{name}:{module.__name__}"
        for module in [root, *submodules]
        for name, value in vars(module).items()
        if isinstance(value, type) and issubclass(value, enum.Enum) and value not in _ENUM_BASES
    )


def generate() -> int:
    locations = enum_locations()
    if not locations:
        print(f"no enums found in {MODULE}; the bindings define several", file=sys.stderr)
        return 1
    command = [sys.executable, "-m", "pybind11_stubgen", "-o", OUT_DIR]
    for location in locations:
        command += ["--enum-class-locations", location]
    command.append(MODULE)
    return subprocess.call(command)


def narrow() -> None:
    for stub in sorted(STUB_DIR.rglob("*.pyi")):
        text = stub.read_text()
        for pattern, replacement in SUBSTITUTIONS:
            text = re.sub(pattern, replacement, text, flags=re.MULTILINE)
        if "numpy.typing." in text and "import numpy.typing" not in text:
            if "import numpy\n" in text:
                text = text.replace("import numpy\n", "import numpy\nimport numpy.typing\n", 1)
            else:
                text = "import numpy\nimport numpy.typing\n" + text
        if not text.startswith("# Generated by"):
            text = HEADER + text
        stub.write_text(text)


def main() -> int:
    if generate() != 0:
        print("pybind11-stubgen failed", file=sys.stderr)
        return 1
    if not STUB_DIR.is_dir():
        print(f"{STUB_DIR} was not produced", file=sys.stderr)
        return 1
    narrow()
    print(f"wrote {len(list(STUB_DIR.rglob('*.pyi')))} stub(s) under {STUB_DIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
